default:
  BD:
    default: "tests/bases_dados/lite.sqlite3"
    lite: "tests/bases_dados/lite.sqlite3"

tests:
  BD:
    default: "tests/bases_dados/lite.sqlite3"
    lite: "tests/bases_dados/lite.sqlite3"
